<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Run</name>
   <tag></tag>
   <elementGuidId>f3859f71-e60e-4d6d-9806-401a33ec43dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#runbtn</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'runbtn' and (text() = 'Run ❯' or . = 'Run ❯')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='runbtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4301a467-9f9b-4625-99f8-e23c7718d46d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>runbtn</value>
      <webElementGuid>139be5f3-3cd1-42fc-8603-596ab6b330d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w3-button w3-bar-item w3-hover-white w3-hover-text-green ga-tryit</value>
      <webElementGuid>49de5614-f041-4e01-826e-7d18e1d22109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>submitTryit(1);uic_prov_run();</value>
      <webElementGuid>98b9aeac-3cf0-4997-80bb-0a7b9aeada7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Run ❯</value>
      <webElementGuid>0268223c-4b91-4335-8cfa-b102e954fd26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;runbtn&quot;)</value>
      <webElementGuid>d748f609-9d28-4734-b054-115f13c39592</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='runbtn']</value>
      <webElementGuid>a9bb77fa-26f1-4c49-8ce0-75fe23268a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='own Java'])[1]/preceding::button[1]</value>
      <webElementGuid>df6cb80d-f93b-45f5-b4d8-d2efd7a398c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Run ❯']/parent::*</value>
      <webElementGuid>0d22a83d-ec83-47bf-9445-9aba97c3b6d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>1fcde47b-54e7-4d1f-bc70-830401a34538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'runbtn' and (text() = 'Run ❯' or . = 'Run ❯')]</value>
      <webElementGuid>78f9203d-4f80-49fb-afed-44f00e4d06d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
