<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_HTML</name>
   <tag></tag>
   <elementGuidId>075a17b8-b3fc-4d97-8887-233efc77e990</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='subtopnav']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.ga-nav.subtopnav_firstitem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>48b54317-2c38-4d77-8817-916812ee8155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/html/default.asp</value>
      <webElementGuid>342ff4e5-e02c-449c-8218-fe7cdcf934fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ga-nav subtopnav_firstitem</value>
      <webElementGuid>4ae7f85d-a7a4-4b2d-a7db-cc4fd8525291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>HTML Tutorial</value>
      <webElementGuid>c60e328c-6de8-488a-acb5-ec0102c2536f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HTML</value>
      <webElementGuid>8956c5c7-429f-4bc0-a11c-6fd55e5704e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subtopnav&quot;)/a[@class=&quot;ga-nav subtopnav_firstitem&quot;]</value>
      <webElementGuid>7f7f66e7-cd60-44a1-b7e9-2cce86d0f1c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/iFrame1/Page_W3Schools Tryit Editor/iframe</value>
      <webElementGuid>8fbafeab-3c7b-4e2d-b325-7fa73bfbcae2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subtopnav']/a</value>
      <webElementGuid>c268a4be-fb0d-439d-b0a3-7b680028e5c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'HTML')])[3]</value>
      <webElementGuid>91888eed-7305-4794-8a7b-00f9c33c2d62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[10]/following::a[2]</value>
      <webElementGuid>62a34cbc-c55e-4e93-a211-ce4c39b73d05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CSS'])[3]/preceding::a[1]</value>
      <webElementGuid>d501f4bf-81b8-4da9-8831-20d03aa7322b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JAVASCRIPT'])[1]/preceding::a[2]</value>
      <webElementGuid>e0eb6fec-0bd3-4684-b0e0-e6401657bbb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/html/default.asp')])[3]</value>
      <webElementGuid>46dae281-2fb8-4c6a-91af-08f5ce6af5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>8a07f9d5-c29c-4162-86dc-db124f6da7b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/html/default.asp' and @title = 'HTML Tutorial' and (text() = 'HTML' or . = 'HTML')]</value>
      <webElementGuid>b2f4dd8a-f0c4-44fe-9fcb-059c3293a83a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
