<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Run_tryhome</name>
   <tag></tag>
   <elementGuidId>2f864679-fa89-49b9-80c7-f0fdd4c4db13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='tryhome']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tryhome</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>11d318e9-e28a-4412-913e-74471336abab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tryhome</value>
      <webElementGuid>98123e3a-2ab4-4333-9c97-17deb9c9ec8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.w3schools.com</value>
      <webElementGuid>599c44df-07bc-4d9f-a3b8-ad98c9c4fd29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>7201fb5b-6cfc-4be1-acea-2e6f00b94fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>w3schools.com Home</value>
      <webElementGuid>d441e820-29c9-40e9-937f-a7c6f3e2919b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w3-button w3-bar-item topnav-icons fa fa-home ga-tryit</value>
      <webElementGuid>b385bcab-b8d0-45cb-b911-1b6c4dc54b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tryhome&quot;)</value>
      <webElementGuid>d5ccb6d8-6d9e-4d8d-8ab6-f943905d4cb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='tryhome']</value>
      <webElementGuid>0e8f077a-e133-49e5-9018-400ecbc9f13d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.w3schools.com')]</value>
      <webElementGuid>8ff507b2-b8ea-4a7a-ab28-ed2dbf285a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>375ab811-f0a6-44f2-ae9d-c8c5a20e55ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'tryhome' and @href = 'https://www.w3schools.com' and @title = 'w3schools.com Home']</value>
      <webElementGuid>a0f2c7e7-770a-4f14-ad7c-12d7daa82e55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
