<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add to eBook cart</name>
   <tag></tag>
   <elementGuidId>fb926f82-3b9c-4a4b-90a7-a12234c06fb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add-to-ebooks-cart-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='add-to-ebooks-cart-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9353d94e-d663-433b-9e85-6f0226713eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-to-ebooks-cart-button</value>
      <webElementGuid>dd2e925f-25e5-4f2e-8ed6-321421b31590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ajax.add-to-ebooks-cart.x</value>
      <webElementGuid>670d1423-76af-416f-871f-8b7550535c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-text a-text-center</value>
      <webElementGuid>a8c76cdf-05fb-4410-9dce-152a7a75c168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>915f84b8-9158-4148-9c47-e8cf017de8a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add to eBook cart</value>
      <webElementGuid>48713a98-5d93-4f2e-93fd-eaf0f06b41bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add to eBook cart </value>
      <webElementGuid>90cfdf0b-b52c-471d-bba4-ec8e79b04ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-to-ebooks-cart-button&quot;)</value>
      <webElementGuid>e350a049-169b-487f-9f64-90c6ffa7e1e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='add-to-ebooks-cart-button']</value>
      <webElementGuid>b891a9e7-da4a-4c6f-ad55-0c13f86c6c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-2']/span/button</value>
      <webElementGuid>bcff47f8-7766-44dd-95b4-a0f0195d79d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amazon Asia-Pacific Holdings Private Limited'])[1]/following::button[1]</value>
      <webElementGuid>8b7feff8-c45c-483c-b8fa-a80c2a5def5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price includes GST'])[1]/following::button[1]</value>
      <webElementGuid>aab1e2ac-71f5-4104-98b2-e8ad3488680d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available in eBooks cart'])[1]/preceding::button[1]</value>
      <webElementGuid>778142e7-e32d-45eb-97a3-af50097780a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View eBooks cart'])[1]/preceding::button[1]</value>
      <webElementGuid>11e048d8-0c58-4387-ba35-a787ffac21dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add to eBook cart']/parent::*</value>
      <webElementGuid>23f12cde-ef3b-46e4-8f19-769e1376cf63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span/span/button</value>
      <webElementGuid>1ce9040d-8a56-49d6-af47-71d0f504251d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'add-to-ebooks-cart-button' and @name = 'ajax.add-to-ebooks-cart.x' and @type = 'button' and (text() = ' Add to eBook cart ' or . = ' Add to eBook cart ')]</value>
      <webElementGuid>126d0310-b62b-4f1b-8e43-ce0c6c4916ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
