<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Book Store API_google_ads_iframe_218_b1b8c3</name>
   <tag></tag>
   <elementGuidId>f09a58fa-7795-47e7-9c49-24cc5ccac827</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='google_ads_iframe_/21849154601,22343295815/Ad.Plus-970x250-1_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>55c2245f-a7e8-4fcd-8f0c-c77c06d40e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>03f8d384-b31c-46c8-b505-a613007dbd78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://53e616a9cf79a648b2d01544da191dfd.safeframe.googlesyndication.com/safeframe/1-0-40/html/container.html</value>
      <webElementGuid>6992c783-9f91-4dac-890d-bae395dcea6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>google_ads_iframe_/21849154601,22343295815/Ad.Plus-970x250-1_0</value>
      <webElementGuid>93fc76c1-239b-403f-a8d9-6b282fbdf52f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>3rd party ad content</value>
      <webElementGuid>08d27fa6-a7ce-4a4d-b786-de3e32f5c2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>9f69cbbc-9fee-45a8-befb-147ab7ef916b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>49fc42b4-3cd4-4976-ab3e-064bff59ec0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5e49256c-ff94-47f6-a332-b5efe75c5bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>970</value>
      <webElementGuid>e78bb22d-87c0-486d-8700-349dba3d8e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>c2d73f01-92d7-44ec-9c8c-378ceb18c467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-is-safeframe</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f5499396-0f7d-4084-8ad4-b934f16ba2bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts allow-top-navigation-by-user-activation</value>
      <webElementGuid>a4915d8f-1640-4865-b0e7-d5e75409e3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>private-state-token-redemption;attribution-reporting</value>
      <webElementGuid>8f8296ce-8e05-4ab2-a36b-1a13eb6d3af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Advertisement</value>
      <webElementGuid>9b102aa5-7f14-4d1e-b87b-baa6be60414f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1bf4e6dd-d82e-47b2-a67d-d74eb8e212d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-google-container-id</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>8cfa5286-2875-4a77-b6f3-def088033aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-load-complete</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>797a808e-d34e-42e9-bc3d-d3d5a0a2a39e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;google_ads_iframe_/21849154601,22343295815/Ad.Plus-970x250-1_0&quot;)</value>
      <webElementGuid>57adde90-f1a8-451b-b09b-bb602ff4c341</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='google_ads_iframe_/21849154601,22343295815/Ad.Plus-970x250-1_0']</value>
      <webElementGuid>c0ace887-a288-4e7d-83d6-bf7722cf2f48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='google_ads_iframe_/21849154601,22343295815/Ad.Plus-970x250-1_0__container__']/iframe</value>
      <webElementGuid>cc7097f5-a715-4da1-8db7-f84d1777b178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/iframe</value>
      <webElementGuid>b4199b23-ddbf-4e29-8219-8b92c189cb46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://53e616a9cf79a648b2d01544da191dfd.safeframe.googlesyndication.com/safeframe/1-0-40/html/container.html' and @id = 'google_ads_iframe_/21849154601,22343295815/Ad.Plus-970x250-1_0' and @title = '3rd party ad content']</value>
      <webElementGuid>e2b8f284-e7da-4c14-89c3-165056ead7bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
