<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>edf6d392-d317-469a-b3fa-aea14ad1af2b</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Advertisement&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='img_anch_COb5zpSu9IoDFQek2AUdbGwTBg']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3c707840-13df-4e57-8930-f058f4e4cd10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://s0.2mdn.net/simgad/16623589174570490515</value>
      <webElementGuid>fe8f5822-6924-4caf-b905-3261fa547332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Advertisement</value>
      <webElementGuid>c097f383-fd88-429a-9284-d8d28c26b8e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>edc23e4c-542e-463f-aad8-9db4724ee248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>970</value>
      <webElementGuid>03488eec-ffd4-4fab-a025-adbde4fd5991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>4abf1a93-2220-41f4-8841-7fdb1dd6d2c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_anch_COb5zpSu9IoDFQek2AUdbGwTBg&quot;)/img[1]</value>
      <webElementGuid>e86652d8-1fc0-4102-868a-44f099e373c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Example1/Page_DEMOQA/iframe_Book Store API_google_ads_iframe_218_b1b8c3</value>
      <webElementGuid>f6a3acc8-3307-44e7-bcb4-7a4207885c75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='img_anch_COb5zpSu9IoDFQek2AUdbGwTBg']/img</value>
      <webElementGuid>75f110df-bb01-483b-b2c4-712a6350646b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Advertisement']</value>
      <webElementGuid>fc6e2ca0-b7aa-449c-ab33-6a48ff005d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>c4cd93f5-5f27-4535-90d9-7304527fbc25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://s0.2mdn.net/simgad/16623589174570490515' and @alt = 'Advertisement']</value>
      <webElementGuid>3bdad266-3ae2-4c88-82ce-885ac83fa211</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
