<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Play video</name>
   <tag></tag>
   <elementGuidId>ea99719e-226e-4351-9a1c-9b1bab2aa4d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.rs_skip.video-control-btn.my-icon-white.lxqb5mp.t1t42cp9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div/div/div/div/div/div[3]/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ad0ef93d-0a61-431e-aecb-418b7657b6bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rs_skip video-control-btn my-icon-white lxqb5mp t1t42cp9</value>
      <webElementGuid>421a1002-ba5a-43ea-9518-cc4968e41366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Play video button</value>
      <webElementGuid>8f6ab5e2-745e-4a58-a725-de82632a1203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>71ed5808-c218-435e-909f-4c734c767edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>78dc97dc-972b-441e-ba22-d6dc4c19066f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-kameleoon-dynamic-class-35fb</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>11ee6ace-1276-4975-bc73-dc454d9a3875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kameleoonlistener-yzi6</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3964db58-7181-4148-b0cc-9b06d4fdad09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Play video</value>
      <webElementGuid>2b6b81de-d995-417f-82d3-e2827d512492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main overflowXClip&quot;]/div[@class=&quot;container   c1tvdg7s f1mvwx8f l1jitq1y c1q9vhy7 h1vrv94s tkqzppl&quot;]/div[@class=&quot;module-group&quot;]/div[@class=&quot;module&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;header header-generic--secondary false&quot;]/div[@class=&quot;header__media&quot;]/div[@class=&quot;header-media c1vj5c55  ll439xg h1vrv94s&quot;]/div[@class=&quot;c1ltgu9w youtube-video-container video-hidden&quot;]/div[@class=&quot;rs_skip video-control-btn my-icon-white lxqb5mp t1t42cp9&quot;]</value>
      <webElementGuid>014a9944-3223-48ca-8efd-60bd19eec38d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/div/div/div/div[3]/div/div/div[2]</value>
      <webElementGuid>6e3c6d65-162a-4bfe-921c-658dcd1d5d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discover Dubai'])[1]/following::div[5]</value>
      <webElementGuid>048647c8-97d1-424c-b09f-4b8382996bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit Dubai'])[4]/following::div[19]</value>
      <webElementGuid>41182269-9e4b-4d3e-bae1-0fa3dccee1c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your journey starts here'])[1]/preceding::div[6]</value>
      <webElementGuid>66040d4b-bed6-4a23-8ac7-e10356622602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]</value>
      <webElementGuid>09383cc9-3ab9-4064-aa32-097371f0efc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Play video' or . = 'Play video')]</value>
      <webElementGuid>65e34818-be1c-4294-ad30-30b945096bd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
